=== PrashantNarahatti/hibernate/NTTWebPage/public/employeeType.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT employees (employee+)>
<!ELEMENT employee (name,contact,department)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ATTLIST employee eid ID #REQUIRED>
<!ATTLIST employee admin (true|false) "false">

=== PrashantNarahatti/hibernate/NTTWebPage/public/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employeeType.dtd">
<employees>
    <employee eid="e1" admin="true">
       <name>John</name>
       <contact>9164768473</contact>
       <department>Sales</department>
    </employee>
     <employee eid="e2" admin="false">
       <name>Ram</name>
       <contact>9164768473</contact>
       <department>IT</department>
    </employee>
     <employee eid="e3" admin="false">
       <name>Pacchu</name>
       <contact>6362762260</contact>
       <department>EEE</department>
    </employee>
     <employee eid="e4" admin="false">
       <name>Pranu</name>
       <contact>9164768473</contact>
       <department>EEE</department>
    </employee>
</employees>
