=== PrashantNarahatti/hibernate/NTTWebPage/public/employeesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/employeesSchema" 
xmlns:tns="http://www.example.org/employeesSchema" 
elementFormDefault="qualified">

<complexType name="employeestype">
     <sequence>
        <element name="employee" type="tns:employeestype" maxOccurs="3" minOccurs="1"></element>
     </sequence>
</complexType>
<complexType name="employeetype">
      <sequence>
          <element name="name" type="string"></element>
          <element name="contact" type="string"></element>
          <element name="department" type="string"></element>
      </sequence>
      <attribute name="eid" type="ID" use="required"></attribute>
      <attribute name="admin" type="boolean"></attribute>
</complexType>
<element name="root" type="tns:employeestype"></element>
</schema>

=== PrashantNarahatti/hibernate/NTTWebPage/public/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/employeesSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/employeesSchema employeesSchema.xsd ">
   <tns:employee eid="e1">
   <tns:name>John</tns:name>
   <tns:contact>9164768473</tns:contact>
   <tns:department>IT</tns:department>
 </tns:employee>
  <tns:employee eid="e2">
  <tns:name>Ram</tns:name>
  <tns:contact>9164768473</tns:contact>
  <tns:department>IT</tns:department>
</tns:employee>
</tns:root>
